// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.4
// Project name: SquareLine_Project

#include "ui.h"
#include "freetype/lv_freetype.h"
#define FREETYPE_FONT_FILE ("/sdcard/simKai.ttf")
lv_obj_t * qr_code ;
lv_obj_t * wp;
lv_obj_t * ui_Label1 ;
char data[24] ="http://cochip.com.cn";
void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    wp = lv_gif_create(ui_Screen1);
    lv_gif_set_src(wp, "S:/test6.gif");
    lv_obj_align(wp, LV_ALIGN_CENTER, 0,-6);//-26


    
    lv_freetype_init(0, 0, 256 * 1024);
    static lv_ft_info_t info;
    info.name = FREETYPE_FONT_FILE;
    info.weight = 16;
    info.style = FT_FONT_STYLE_NORMAL;
    info.mem = NULL;
    if(!lv_ft_font_init(&info)) {
        LV_LOG_ERROR("create failed.");
    }
    /*ui_Label1 = lv_label_create(ui_Screen1);
    lv_label_set_recolor(ui_Label1, true);  
    lv_obj_set_width(ui_Label1, 64);
    lv_obj_set_height(ui_Label1, 32);
    lv_obj_set_x(ui_Label1, 0);
    lv_obj_set_y(ui_Label1, 0);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Label1, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_Label1, "#0000ff 合##00ffff 芯##ffff00 谷##ff00ff 微##00ff00 电##00ffff 子 #"); 
    lv_obj_set_style_text_font(ui_Label1, &chinese_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_flag(ui_Label1, LV_OBJ_FLAG_HIDDEN);   */
   // lv_obj_set_style_text_font(ui_Label1, info.font, LV_PART_MAIN | LV_STATE_DEFAULT);


    lv_color_t bg_color = lv_palette_lighten(LV_PALETTE_LIGHT_BLUE, 5);
    lv_color_t fg_color = lv_palette_darken(LV_PALETTE_NONE, 4);
    qr_code = lv_qrcode_create(ui_Screen1, 32, fg_color, bg_color);
    lv_qrcode_update(qr_code, data, strlen(data));
    lv_obj_center(qr_code);
    lv_obj_set_style_border_color(qr_code, bg_color, 0);
    lv_obj_set_style_border_width(qr_code, 1, 0); 

   /* lv_obj_t * ui_Label2= lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_obj_set_x(ui_Label2, 0);
    lv_obj_set_y(ui_Label2, 9);
    lv_label_set_long_mode(ui_Label2, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_Label2, "创意设计");
    lv_obj_set_style_text_font(ui_Label2, info.font, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
*/

    
   // lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  /* ui_Image1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image1, &ui_img_happy_santa_png);
    lv_obj_set_width(ui_Image1, 64);
    lv_obj_set_height(ui_Image1, 32);
    lv_obj_set_x(ui_Image1, 20);
    lv_obj_set_y(ui_Image1, -3);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image1, 150);

    ui_Spinner1 = lv_spinner_create(ui_Screen1, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 24);
    lv_obj_set_height(ui_Spinner1, 24);
    lv_obj_set_x(ui_Spinner1, -18);
    lv_obj_set_y(ui_Spinner1, 0);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_width(ui_Spinner1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_Spinner1, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);*/


}
